# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90b2d8639864a129ea6780398b4a5e152c3738663ccf039bcb83b725642e6068698d0685094d41c8b1707f5b3b5fafffcce09d518218f23fd8d9b7ca0cdfaa78

test:
  secret_key_base: 4e224d588dac8a5b33d6df96f5eec7325e7e57ef4b3e9deec2ff499e8a2c97c9bd1772a624e2027b99ac84f7d5b07744b9410aa4807a6664fee94d584fff5f0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
